/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author ASUS
 */
public class TrangChu extends javax.swing.JFrame {
    /**
     * Creates new form TrangChu
     */
    public TrangChu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneMain = new javax.swing.JScrollPane();
        JPanelMain = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnQuanLybanHang = new javax.swing.JButton();
        btnQuanLyHangHoa = new javax.swing.JButton();
        btnQuanLyKho = new javax.swing.JButton();
        btnQuanLyDoanhThu = new javax.swing.JButton();
        btnQuanLyNhanVien = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1500, 1000));
        setResizable(false);

        paneMain.setBackground(new java.awt.Color(255, 255, 255));

        JPanelMain.setAlignmentX(0.0F);
        JPanelMain.setAlignmentY(0.0F);
        JPanelMain.setPreferredSize(new java.awt.Dimension(1500, 1000));

        javax.swing.GroupLayout JPanelMainLayout = new javax.swing.GroupLayout(JPanelMain);
        JPanelMain.setLayout(JPanelMainLayout);
        JPanelMainLayout.setHorizontalGroup(
            JPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );
        JPanelMainLayout.setVerticalGroup(
            JPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );

        paneMain.setViewportView(JPanelMain);

        btnQuanLybanHang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLybanHang.setForeground(new java.awt.Color(219, 41, 29));
        btnQuanLybanHang.setText("Quản lý bán hàng");
        btnQuanLybanHang.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQuanLybanHang.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQuanLybanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLybanHangActionPerformed(evt);
            }
        });

        btnQuanLyHangHoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLyHangHoa.setForeground(new java.awt.Color(219, 41, 29));
        btnQuanLyHangHoa.setText("Quản lý hàng hóa");
        btnQuanLyHangHoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQuanLyHangHoa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnQuanLyKho.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLyKho.setForeground(new java.awt.Color(219, 41, 29));
        btnQuanLyKho.setText("Quản lý kho");
        btnQuanLyKho.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQuanLyKho.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnQuanLyDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLyDoanhThu.setForeground(new java.awt.Color(219, 41, 29));
        btnQuanLyDoanhThu.setText("Quản lý doanh thu");
        btnQuanLyDoanhThu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQuanLyDoanhThu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnQuanLyNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnQuanLyNhanVien.setForeground(new java.awt.Color(219, 41, 29));
        btnQuanLyNhanVien.setText("Quản lý nhân viên");
        btnQuanLyNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQuanLyNhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQuanLyNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanLyNhanVienActionPerformed(evt);
            }
        });

        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(219, 41, 29));
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQuanLybanHang)
                .addGap(18, 18, 18)
                .addComponent(btnQuanLyHangHoa)
                .addGap(18, 18, 18)
                .addComponent(btnQuanLyKho)
                .addGap(18, 18, 18)
                .addComponent(btnQuanLyDoanhThu)
                .addGap(18, 18, 18)
                .addComponent(btnQuanLyNhanVien)
                .addGap(18, 18, 18)
                .addComponent(btnDangXuat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDangXuat)
                    .addComponent(btnQuanLyNhanVien)
                    .addComponent(btnQuanLyDoanhThu)
                    .addComponent(btnQuanLyKho)
                    .addComponent(btnQuanLyHangHoa)
                    .addComponent(btnQuanLybanHang))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paneMain, javax.swing.GroupLayout.DEFAULT_SIZE, 1224, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneMain, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuanLyNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLyNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuanLyNhanVienActionPerformed

    private void btnQuanLybanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanLybanHangActionPerformed
        QuanLyBanHang qlbh = new QuanLyBanHang();
        JPanelMain.removeAll();
        JPanelMain.add(qlbh.getContentPane());
        JPanelMain.revalidate();
    }//GEN-LAST:event_btnQuanLybanHangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        new TrangChu().setPreferredSize(screenSize);
        new TrangChu().setExtendedState(JFrame.MAXIMIZED_BOTH);
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TrangChu().setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                new TrangChu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelMain;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnQuanLyDoanhThu;
    private javax.swing.JButton btnQuanLyHangHoa;
    private javax.swing.JButton btnQuanLyKho;
    private javax.swing.JButton btnQuanLyNhanVien;
    private javax.swing.JButton btnQuanLybanHang;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane paneMain;
    // End of variables declaration//GEN-END:variables
    
}

